### ISSUE TITLE
Can't install econml with tensorflow error

### ISSUE THREAD

**Issue by skfkrh** [microsoft/EconML#271]
I tried installing econml with pip install command but unable to. pasting the error message I got.
I also tried multiple version of econml installation to see if any of it works but none worked.

ERROR: Could not find a version that satisfies the requirement tensorflow==1.* (from econml==0.6.0) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.* (from econml==0.6.0)

**Comment by kbattocchi** [comment]
Thanks for the report.  Are you by any chance using python 3.8?  If so, then we've recently made a fix to this issue (see #210) and hope to have a new release out in the next week or so that includes those changes.

**Comment by skfkrh** [comment]
I lower the version of python and installed it but when I try to install dml, it gives me another import error.

from econml.dml import DMLCateEstimator
Traceback (most recent call last):

  File "<ipython-input-9-a4f0c403a40e>", line 1, in <module>
    from econml.dml import DMLCateEstimator

  File "C:\Users\minkan\AppData\Local\Continuum\anaconda3\lib\site-packages\econml\dml.py", line 39, in <module>
    from .utilities import (shape, reshape, ndim, hstack, cross_product, transpose, inverse_onehot,

  File "C:\Users\minkan\AppData\Local\Continuum\anaconda3\lib\site-packages\econml\utilities.py", line 8, in <module>
    import sparse as sp

  File "C:\Users\minkan\AppData\Local\Continuum\anaconda3\lib\site-packages\sparse\__init__.py", line 5, in <module>
    from ._io import save_npz, load_npz

  File "C:\Users\minkan\AppData\Local\Continuum\anaconda3\lib\site-packages\sparse\_io.py", line 4, in <module>
    from ._compressed import GCXS

  File "C:\Users\minkan\AppData\Local\Continuum\anaconda3\lib\site-packages\sparse\_compressed\__init__.py", line 1, in <module>
    from .compressed import GCXS

  File "C:\Users\minkan\AppData\Local\Continuum\anaconda3\lib\site-packages\sparse\_compressed\compressed.py", line 13, in <module>
    from .convert import uncompress_dimension, _transpose, _1d_reshape

  File "C:\Users\minkan\AppData\Local\Continuum\anaconda3\lib\site-packages\sparse\_compressed\convert.py", line 7, in <module>
    from numba.typed import List

ImportError: cannot import name 'List' from 'numba.typed' (C:\Users\minkan\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\typed\__init__.py)
