### ISSUE TITLE
ImportError - Circular Import RScorer

### ISSUE THREAD

**Issue by fmssn** [microsoft/EconML#500]
When importing the RScorer, it raises the Error of:

```
from econml.score import RScorer

Traceback (most recent call last):

  File "<ipython-input-4-b872580a7952>", line 1, in <module>
    from econml.score import RScorer

  File "C:\Users\fabia\anaconda3\lib\site-packages\econml\score\__init__.py", line 9, in <module>
    from .rscorer import RScorer

  File "C:\Users\fabia\anaconda3\lib\site-packages\econml\score\rscorer.py", line 4, in <module>
    from ..dml import LinearDML

  File "C:\Users\fabia\anaconda3\lib\site-packages\econml\dml\__init__.py", line 40, in <module>
    from .causal_forest import CausalForestDML

  File "C:\Users\fabia\anaconda3\lib\site-packages\econml\dml\causal_forest.py", line 25, in <module>
    from ..score import RScorer

ImportError: cannot import name 'RScorer' from partially initialized module 'econml.score' (most likely due to a circular import) (C:\Users\fabia\anaconda3\lib\site-packages\econml\score\__init__.py)
```

There is however no problem importing when importing CausalForestDML beforehand like:
```
from econml.dml import CausalForestDML
from econml.score import RScorer
```

I am not sure if I am missing something, but from looking at previous issues it does not seem to have always been the case. I tried this on two different computers with fresh installations, so it should be easy to reproduce.

**Comment by vsyrgkanis** [comment]
Oh! That seems a bug indeed, as Rscorer tries to load CausalForestDML which tries to load Rscrorer. Thanks for raising this!
