### ISSUE TITLE
is there any version supporting GPU core?

### ISSUE THREAD

**Issue by ysong2123** [microsoft/EconML#582]

**Comment by ysong2123** [comment]
append some error log:

>>> from econml.dr import ForestDRLearner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ysong2/econml/econml/dr/__init__.py", line 4, in <module>
    from ._drlearner import (DRLearner, LinearDRLearner, SparseLinearDRLearner, ForestDRLearner)
  File "/home/ysong2/econml/econml/dr/_drlearner.py", line 51, in <module>
    from ..grf import RegressionForest
  File "/home/ysong2/econml/econml/grf/__init__.py", line 14, in <module>
    from ._criterion import LinearMomentGRFCriterion, LinearMomentGRFCriterionMSE
ModuleNotFoundError: No module named 'econml.grf._criterion'
>>> import numpy as np
>>> from econml.grf import RegressionForest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ysong2/econml/econml/grf/__init__.py", line 14, in <module>
    from ._criterion import LinearMomentGRFCriterion, LinearMomentGRFCriterionMSE
ModuleNotFoundError: No module named 'econml.grf._criterion'
>>> from econml.grf._base_grftree import GRFTree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ysong2/econml/econml/grf/__init__.py", line 14, in <module>
    from ._criterion import LinearMomentGRFCriterion, LinearMomentGRFCriterionMSE
ModuleNotFoundError: No module named 'econml.grf._criterion'
>>> from econml.tree._tree import Tree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ysong2/econml/econml/tree/__init__.py", line 4, in <module>
    from ._criterion import Criterion, RegressionCriterion, MSE
ModuleNotFoundError: No module named 'econml.tree._criterion'

**Comment by ysong2123** [comment]
>>> from econml.dr import ForestDRLearner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/econml/econml/dr/__init__.py", line 4, in <module>
    from ._drlearner import (DRLearner, LinearDRLearner, SparseLinearDRLearner, ForestDRLearner)
  File "/home/econml/econml/dr/_drlearner.py", line 51, in <module>
    from ..grf import RegressionForest
  File "/home/econml/econml/grf/__init__.py", line 14, in <module>
    from ._criterion import LinearMomentGRFCriterion, LinearMomentGRFCriterionMSE
ModuleNotFoundError: No module named 'econml.grf._criterion'
>>> import numpy as np
>>> from econml.grf import RegressionForest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/econml/econml/grf/__init__.py", line 14, in <module>
    from ._criterion import LinearMomentGRFCriterion, LinearMomentGRFCriterionMSE
ModuleNotFoundError: No module named 'econml.grf._criterion'
>>> from econml.grf._base_grftree import GRFTree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/econml/econml/grf/__init__.py", line 14, in <module>
    from ._criterion import LinearMomentGRFCriterion, LinearMomentGRFCriterionMSE
ModuleNotFoundError: No module named 'econml.grf._criterion'
>>> from econml.tree._tree import Tree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/econml/econml/tree/__init__.py", line 4, in <module>
    from ._criterion import Criterion, RegressionCriterion, MSE
ModuleNotFoundError: No module named 'econml.tree._criterion'

**Comment by kbattocchi** [comment]
We provide pre-built wheels for the most common Linux, Windows, and macOS architectures, as well as a source distribution for the package which should be able to be installed in most other environments.  Can you run `pip uninstall econml`, and then see if there are any warnings or errors when running `pip install econml` again?  Also, could you provide the output of `pip list`?  Thanks.

**Comment by kbattocchi** [comment]
Were there any warnings generated during the installation of econml?  Do you still get the same stack trace when importing `ForestDRLearner`?

**Comment by ysong2123** [comment]
![Uploading Screen Shot 2022-03-09 at 10.47.56 AM.png…]()

**Comment by ysong2123** [comment]
only import econml, it is ok.   but 'from econml.dr import ForestDRLearner '  i got error: 'ModuleNotFoundError: No module named 'econml.dr' '
