### ISSUE TITLE
Issue with importing Rscore

### ISSUE THREAD

**Issue by divyat09** [microsoft/EconML#611]
I am facing this issue while importing RScore. This did not use to be the case before and I did not update the library as well.

**Command:**  from econml.score import RScorer

**Error Log:**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/causal_val_env/lib/python3.7/site-packages/econml/score/__init__.py", line 9, in <module>
    from .rscorer import RScorer
  File "/causal_val_env/lib/python3.7/site-packages/econml/score/rscorer.py", line 4, in <module>
    from ..dml import LinearDML
  File "/causal_val_env/lib/python3.7/site-packages/econml/dml/__init__.py", line 39, in <module>
    from .causal_forest import CausalForestDML
  File "/causal_val_env/lib/python3.7/site-packages/econml/dml/causal_forest.py", line 25, in <module>
    from ..score import RScorer
ImportError: cannot import name 'RScorer' from 'econml.score' (/causal_val_env/lib/python3.7/site-packages/econml/score/__init__.py)

**Comment by kbattocchi** [comment]
Apologies for the inconvenience; this was also reported in #500, and has been fixed in our code but not made it into a new release yet.  One workaround is to first run `from econml.dml import CausalForestDML` before trying to import `RScorer`.

**Comment by divyat09** [comment]
Thanks for the quick reply! Sure, I can import in the way your recommended for now.
